GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/
60a5c7011951281e7cb307f7

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name" : "Amazing Person",
    "subscribedToChannel" : "patxu"
}

###

DELETE http://localhost:3000/subscribers/
60a5c7011951281e7cb307f7

###

PATCH  http://localhost:3000/subscribers/
60a5c89b10ad86223cfe7207
Content-Type: application/json

{
    "name" : "new name",
    "subscribedToChannel" : "new subscriedToChannel"
}